#!/bin/bash
# Requirements:
# pandoc
# pandoc-citeproc
# texlive-full
# librsvg2-bin
cat dissertation.md > tmp.md
for i in contents/{0..6}*; do
  cat "$i" >> tmp.md
  echo "" >> tmp.md
  echo "" >> tmp.md
done
scripts/mwc.py tmp.md
cat "contents/7-refs-appendices.md" >> tmp.md
echo "" >> tmp.md
day=$(date '+%d')
case $day in
'01')
  dateSuffix="st"
  ;;
'02')
  dateSuffix="nd"
  ;;
'03')
  dateSuffix="rd"
  ;;
*)
  dateSuffix="th"
  ;;
esac
date=$(date "+%_d\textsuperscript{$dateSuffix} %B %Y")
pandoc --variable date="$date" --filter pandoc-citeproc -o output.pdf tmp.md
