#!/bin/bash
total=0
minimum=7000
maximum=14000
for i in contents/{0..6}*; do
  padded=$(printf %-50s $i)
  wc=$(scripts/mwc.py "$i")
  echo "$padded: $wc"
  total=$((total+wc))
done
echo $total
echo "$((minimum-total)) remaining"
