#!/bin/bash
# scripts/build
# CURRENT_WORD_COUNT=$(pdftotext output.pdf - | tr -d '.' | wc -w)
CURRENT_WORD_COUNT=$(ps2ascii output.pdf | wc -w)
TARGET_WORD_COUNT=1000
PERCENTAGE_WORD_COUNT=$(echo "scale=2; $CURRENT_WORD_COUNT*100/$TARGET_WORD_COUNT" | bc)
[ $CURRENT_WORD_COUNT -gt $TARGET_WORD_COUNT ] && echo "Word count $(($CURRENT_WORD_COUNT - $TARGET_WORD_COUNT)) over limit." || echo "Word count: $CURRENT_WORD_COUNT/$TARGET_WORD_COUNT. $PERCENTAGE_WORD_COUNT% complete."
